version: '3.8'
services:
  web:
    build: .
    container_name: strojni_dilna_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - strojni_dilna_network
    environment:
      - DB_HOST=db
      - DB_NAME=strojni_dilna
      - DB_USER=root
      - DB_PASS=root_password
  db:
    image: mysql:8.0
    container_name: strojni_dilna_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: strojni_dilna
      MYSQL_USER: web_user
      MYSQL_PASSWORD: web_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - strojni_dilna_network
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: strojni_dilna_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - strojni_dilna_network
volumes:
  mysql_data:
networks:
  strojni_dilna_network:
    driver: bridge